### ISSUE TITLE
blob_size2 undefined in cellolib.py if size2 is None

### ISSUE THREAD

**Issue by dahlbma** [dahlbma/cello#12]
If size2 is None a runtime error occurs and the application stops working. I did a dirty fix to avoid the problem and compiled a new version.  See line 173 in cellolib.py

This is the error:
Traceback (most recent call last):
  File "platesscreen.py", line 206, in check_plate_search_input
  File "platesscreen.py", line 254, in plateSearch
  File "cellolib.py", line 174, in plate_to_html
UnboundLocalError: local variable 'blob_size2' referenced before assignment

**Comment by ChrillePille** [comment]
Fixed in f24da74ad65f9a6f785d5f7436b91af600ceceee
